DISM.exe /online /Cleanup-Image /StartComponentCleanup

DISM.exe /online /Cleanup-Image /SPSuperseded

DISM.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase

@rem features
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-All /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-Tools-All /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-Management-Clients /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-Management-PowerShell /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:LegacyComponents /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:DirectPlay /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:SNMP /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WMISnmpProvider /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:Windows-Identity-Foundation /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MicrosoftWindowsPowerShellV2Root /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MicrosoftWindowsPowerShellV2 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:DirectoryServices-ADAM-Client /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-WebServerRole /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-WebServer /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-CommonHttpFeatures /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpErrors /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpRedirect /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ApplicationDevelopment /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-NetFxExtensibility /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-NetFxExtensibility45 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-HealthAndDiagnostics /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpLogging /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-LoggingLibraries /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-RequestMonitor /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpTracing /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-Security /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-URLAuthorization /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-RequestFiltering /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-IPSecurity /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-Performance /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpCompressionDynamic /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-WebServerManagementTools /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ManagementScriptingTools /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-IIS6ManagementCompatibility /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-Metabase /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WAS-WindowsActivationService /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WAS-ProcessModel /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WAS-NetFxEnvironment /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WAS-ConfigurationAPI /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-HostableWebCore /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-CertProvider /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-WindowsAuthentication /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-DigestAuthentication /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ClientCertificateMappingAuthentication /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-IISCertificateMappingAuthentication /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ODBCLogging /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-StaticContent /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-DefaultDocument /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-DirectoryBrowsing /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-WebDAV /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-WebSockets /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ApplicationInit /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ASPNET /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ASPNET45 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ASP /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-CGI /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ISAPIExtensions /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ISAPIFilter /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ServerSideIncludes /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-CustomLogging /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-BasicAuthentication /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpCompressionStatic /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ManagementConsole /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-ManagementService /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-WMICompatibility /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-LegacyScripts /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-LegacySnapIn /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-FTPServer /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-FTPSvc /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:IIS-FTPExtensibility /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MSMQ-Container /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MSMQ-Server /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MSMQ-Triggers /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MSMQ-ADIntegration /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MSMQ-HTTP /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MSMQ-Multicast /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MSMQ-DCOMProxy /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WCF-Services45 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WCF-HTTP-Activation45 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WCF-TCP-Activation45 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WCF-Pipe-Activation45 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WCF-MSMQ-Activation45 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WCF-TCP-PortSharing45 /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WCF-HTTP-Activation /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:WCF-NonHTTP-Activation /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:RasCMAK /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:RasRip /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:MSRDC-Infrastructure /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:TelnetServer /Remove /NoRestart
DISM.exe /Online /Disable-Feature /featurename:SMB1Protocol /Remove /NoRestart

